version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/sheroes
  - source: index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/php-deploy.sh
  AfterInstall:
    - location: scripts/rmappspec.sh
